### ISSUE TITLE
media_kit compilation issue in android

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#1213]
android app compilation failed in `media_kit` stage.
```
Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:51908/VPhxVIFA_hM=/ws
V/uk.orth.push.PushHostHandlers( 6696): Ignoring this method because it is used in a separate listener (`BackgroundFlutterAppLauncher.kt`), when the Flutter app is launched manually.
I/flutter ( 6696):
I/flutter ( 6696): --------------------------------------------------------------------------------
I/flutter ( 6696): media_kit: ERROR: MediaKit.ensureInitialized
I/flutter ( 6696): This indicates that one or more required dependencies could not be located.
I/flutter ( 6696):
I/flutter ( 6696): Refer to "Installation" section of the README for further details:
I/flutter ( 6696): GitHub  : https://github.com/media-kit/media-kit#installation
I/flutter ( 6696): pub.dev : https://pub.dev/packages/media_kit#installation
I/flutter ( 6696):
I/flutter ( 6696): TIP: Copy-paste required packages from the above link to your pubspec.yaml.
I/flutter ( 6696):
I/flutter ( 6696): If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
I/flutter ( 6696): --------------------------------------------------------------------------------
E/flutter ( 6696): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv.so. Please ensure it's presence in the APK.
E/flutter ( 6696): #0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:78:9)
E/flutter ( 6696): #1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47:17)
E/flutter ( 6696): #2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:36:9)
E/flutter ( 6696): #3      VideoPlayerMediaKit.ensureInitialized (package:video_player_media_kit/video_player_media_kit.dart:58:16)
E/flutter ( 6696): #4      main (package:acter/main.dart:24:23)
E/flutter ( 6696): <asynchronous suspension>
```
Before `media_kit` failed in windows too.
This log is outputted at top of debug console in vs code.
This was tested in Android 7.0 Google APIs x86_64 emulator.

**Comment by kumarpalsinh25** [comment]
@bitfriend,
I have checked the code and it seems like it is already fixed by [PR Hot-fix : Media_kit support](https://github.com/acterglobal/a3/pull/1201).

So closing this issue.
