### ISSUE TITLE
FilePicker crashes on android

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#1803]
#1802 introduced saving the file. We could provide the same for Android, would it not crash after returning from the folder-selection screen with:

```

E/AndroidRuntime(12214): FATAL EXCEPTION: main
E/AndroidRuntime(12214): Process: global.acter.a3, PID: 12214
E/AndroidRuntime(12214): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4962, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/16 flg=0x43 }} to activity {global.acter.a3/global.acter.app.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime(12214): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
E/AndroidRuntime(12214): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5379)
E/AndroidRuntime(12214): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(12214): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(12214): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(12214): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(12214): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
E/AndroidRuntime(12214): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12214): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(12214): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(12214): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(12214): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12214): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(12214): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(12214): Caused by: java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime(12214): 	at java.io.FileOutputStream.write(FileOutputStream.java:379)
E/AndroidRuntime(12214): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate.onActivityResult(FilePickerDelegate.java:96)
E/AndroidRuntime(12214): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:774)
E/AndroidRuntime(12214): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:422)
E/AndroidRuntime(12214): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:857)
E/AndroidRuntime(12214): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:884)
E/AndroidRuntime(12214): 	at android.app.Activity.dispatchActivityResult(Activity.java:8385)
E/AndroidRuntime(12214): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5333)
E/AndroidRuntime(12214): 	... 13 more
I/Process (12214): Sending signal. PID: 12214 SIG: 9
Lost connection to device.

**Comment by gnunicorn** [comment]
fixed by #2182
