### ISSUE TITLE
White screen showing on cancel session logout dialog

### ISSUE THREAD

**Issue by kumarpalsinh25** [acterglobal/a3#1908]
https://github.com/acterglobal/a3/assets/51526480/a326b5e5-b37c-4f2f-8257-ea3a5571d838

**Comment by gnunicorn** [comment]
@kumarpalsinh25 can you bug-send the logs from that run?

**Comment by gnunicorn** [comment]
https://github.com/acterglobal/a3-meta/issues/332

**Comment by gnunicorn** [comment]
logs don't show anything unusual...

**Comment by kumarpalsinh25** [comment]
Able to easily reproduced from android emulator.

<img width="1500" alt="Screenshot 2024-07-01 at 9 58 04 PM" src="https://github.com/acterglobal/a3/assets/51526480/bb9b6848-f604-4988-b39c-169750a9be26">

**Comment by kumarpalsinh25** [comment]
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/kumarpalsinh/Projects/Acter/a3/app/lib/main.dart:91:26
When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4743:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4757:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4776:12)
#3      Theme.of (package:flutter/src/material/theme.dart:105:53)
#4      SessionCard.onLogout.<anonymous closure> (package:acter/features/settings/widgets/session_card.dart:100:34)
#5      Builder.build (package:flutter/src/widgets/basic.dart:7695:48)
#6      StatelessElement.build (package:flutter/src/widgets/framework.dart:5557:49)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487:15)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#13     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#17     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#21     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#29     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#33     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#39     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#43     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#49     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#55     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#62     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#64     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#71     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#77     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#78     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#83     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#85     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#89     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#93     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#98     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#102    StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#106    StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#112    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#116    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#119    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#121    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#124    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#126    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#129    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#131    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
#132    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:21)
#133    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#134    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#135    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#136    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#137    _invoke (dart:ui/hooks.dart:312:13)
#138    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#139    _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```

https://github.com/acterglobal/a3/assets/51526480/85d8f677-6a20-476c-9be4-651527afa0a1
