### ISSUE TITLE
blank dashboard

### ISSUE THREAD

**Issue by gnunicorn** [acterglobal/a3#680]
starting nightly from today, the dashboard doesn't render on android and I get the following in logcat:

```


06-28 11:46:28.786  9785 13039 E global.acter.app: acter::platform::native: [2023-06-28][10:46:28][acter::platform::native][ERROR] Null check operator used on a null value
06-28 11:46:28.788  9785 13039 E global.acter.app: acter::platform::native: [2023-06-28][10:46:28][acter::platform::native][ERROR] #0      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:761)
06-28 11:46:28.788  9785 13039 E global.acter.app: #1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.788  9785 13039 E global.acter.app: #2      _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #3      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.788  9785 13039 E global.acter.app: #4      RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3821)
06-28 11:46:28.788  9785 13039 E global.acter.app: #5      _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.788  9785 13039 E global.acter.app: #7      _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #8      RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:188)
06-28 11:46:28.788  9785 13039 E global.acter.app: #9      _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #10     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:188)
06-28 11:46:28.788  9785 13039 E global.acter.app: #11     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #12     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:188)
06-28 11:46:28.788  9785 13039 E global.acter.app: #13     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #14     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.788  9785 13039 E global.acter.app: #15     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #16     RenderFollowerLayer.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:4995)
06-28 11:46:28.788  9785 13039 E global.acter.app: #17     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:849)
06-28 11:46:28.788  9785 13039 E global.acter.app: #18     BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:774)
06-28 11:46:28.788  9785 13039 E global.acter.app: #19     RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2598)
06-28 11:46:28.788  9785 13039 E global.acter.app: #20     RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2592)
06-28 11:46:28.788  9785 13039 E global.acter.app: #21     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.788  9785 13039 E global.acter.app: #23     RenderClipRect.hitTest (package:flutter/src/rendering/proxy_box.dart:1558)
06-28 11:46:28.788  9785 13039 E global.acter.app: #24     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.788  9785 13039 E global.acter.app: #26     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2903)
06-28 11:46:28.788  9785 13039 E global.acter.app: #27     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:810)
06-28 11:46:28.788  9785 13039 E global.acter.app: #28     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2898)
06-28 11:46:28.788  9785 13039 E global.acter.app: #29     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:420)
06-28 11:46:28.788  9785 13039 E global.acter.app: #30     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.788  9785 13039 E global.acter.app: #31     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.788  9785 13039 E global.acter.app: #33     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.788  9785 13039 E global.acter.app: #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.788  9785 13039 E global.acter.app: #35     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:2042)
06-28 11:46:28.788  9785 13039 E global.acter.app: #36     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.798  9785 13039 E global.acter.app: acter::platform::native: [2023-06-28][10:46:28][acter::platform::native][ERROR] Null check operator used on a null value
06-28 11:46:28.801  9785 13039 E global.acter.app: acter::platform::native: [2023-06-28][10:46:28][acter::platform::native][ERROR] #0      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:761)
06-28 11:46:28.801  9785 13039 E global.acter.app: #1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.801  9785 13039 E global.acter.app: #2      _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #3      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.801  9785 13039 E global.acter.app: #4      RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3821)
06-28 11:46:28.801  9785 13039 E global.acter.app: #5      _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.801  9785 13039 E global.acter.app: #7      _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #8      RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:188)
06-28 11:46:28.801  9785 13039 E global.acter.app: #9      _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #10     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:188)
06-28 11:46:28.801  9785 13039 E global.acter.app: #11     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #12     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:188)
06-28 11:46:28.801  9785 13039 E global.acter.app: #13     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #14     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.801  9785 13039 E global.acter.app: #15     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #16     RenderFollowerLayer.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:4995)
06-28 11:46:28.801  9785 13039 E global.acter.app: #17     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:849)
06-28 11:46:28.801  9785 13039 E global.acter.app: #18     BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:774)
06-28 11:46:28.801  9785 13039 E global.acter.app: #19     RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2598)
06-28 11:46:28.801  9785 13039 E global.acter.app: #20     RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2592)
06-28 11:46:28.801  9785 13039 E global.acter.app: #21     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.801  9785 13039 E global.acter.app: #23     RenderClipRect.hitTest (package:flutter/src/rendering/proxy_box.dart:1558)
06-28 11:46:28.801  9785 13039 E global.acter.app: #24     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.801  9785 13039 E global.acter.app: #26     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2903)
06-28 11:46:28.801  9785 13039 E global.acter.app: #27     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:810)
06-28 11:46:28.801  9785 13039 E global.acter.app: #28     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2898)
06-28 11:46:28.801  9785 13039 E global.acter.app: #29     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:420)
06-28 11:46:28.801  9785 13039 E global.acter.app: #30     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.801  9785 13039 E global.acter.app: #31     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.801  9785 13039 E global.acter.app: #33     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
06-28 11:46:28.801  9785 13039 E global.acter.app: #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2523)
06-28 11:46:28.801  9785 13039 E global.acter.app: #35     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:2042)
06-28 11:46:28.801  9785 13039 E global.acter.app: #36     _RenderLayoutBuilderPreserveBaseline.hitTestChildren (package:flutter_math_fork/src/render/layout/layout_builder_baseline.dart:74)
```

**Comment by gnunicorn** [comment]
This is fixed.
